baseURL = "https://www.claydrop.com"
metaDataFormat = "yaml"
title = "ClayDrop Research USA"
theme = "blist"
publishDir = "public"
show_reading_time = true
enableRobotsTXT = true
disqusShortname = "relaxedincome"
googleAnalytics = 'G-DCFGQJK09Y'

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = false

timeout = 60000

[permalinks]
  posts = "/:filename"
  blog = "/:filename"
  page = "/:filename"


[taxonomies]
  tag = 'tag'

[languages]
  [languages.en]
    contentDir = "content/en"
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Hey! I'm Aria Smith"
      introSubtitle = "Texan who enjoys blogging and painting"
      introPhoto = "/tpdne_poster.png"
      logo = "/blist-logo.png"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1
#    [[languages.en.menu.main]]
#        name = "Category"
#        url = "category"
#        weight = 2
    [[languages.en.menu.main]]
        name = "Tags"
        url = "tag"
        weight = 2
#    [[languages.en.menu.main]]
#        name = "Subscribe"
#        url = "page/subscribe"
#        weight = 4

#    [[languages.en.menu.main]]
#        name = "About"
#        url = "page/about/"
#        weight = 3

#    [[languages.en.menu.main]]
#        name = "Top Post"
#        url = "/en/blog/emoji-support/"
#        weight = 4

[params]
  [[params.hugoLeaflet.css]]
  href = "https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
  crossorigin = ""

    [params.hugoLeaflet.css.params]
    integrity = "sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="

  [[params.hugoLeaflet.css]]
  href = "https://unpkg.com/@raruto/leaflet-elevation@1.1.1/dist/leaflet-elevation.css"

  [[params.hugoLeaflet.css]]
  href = "/css/leaflet.extra-markers.min.css"

  [[params.hugoLeaflet.js]]
  src = "https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
  crossorigin = ""

    [params.hugoLeaflet.js.params]
    integrity = "sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="

  [[params.hugoLeaflet.js]]
  src = "/js/leaflet.elevation.js"

  [[params.hugoLeaflet.js]]
  src = "/js/leaflet.hugo.js"

  [[params.hugoLeaflet.js]]
  src = "/js/leaflet.extra-markers.min.js"


  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2021 - BeaconstreetUSA.com · All rights reserved"
  #favicon = "/icons8-favorite-16.png"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = true

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = false

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

# Comments system
[params.comments]
  # Supports disqus, giscus and utterances
  # Check hugo docs for setting up disqus
  system = "disqus"

  # Options for utterances, exclude hyphens
  # repo = ""
  # issueterm = ""
  # theme = ""

#[[menu.main]]
#  name = "About"
#  url = "/about"



[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    unsafe = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
